name: 'GitGudSimilarIssues Action'

description: 'Get similar issues based on an issue title from GitGudIssues'

inputs:
  issuetitle:  
    description: 'Issue to analyze title'
    required: true
    default: 'Hello World'
  repo:
    description: 'Repository to analyze'
    required: true
  similaritytolerance:
    description: 'How low of a tolerance you will show issues for. 0 is not similar, 1 is identical'
    required: false
    default: "0.7"

outputs:
  message: 
    description: 'Output message'

runs:
  using: 'node20'
  main: 'dist/index.js'