name: 'GitGudSimilarIssues Action'

description: 'Get similar issues based on an issue title from GitGudIssues'

inputs:
  issuetitle:  
    description: 'Issue to analyze title'
    required: true
    default: 'Hello World'
  repo:
    description: 'Repository to analyze'
    required: true
  eucldistancetolerance:
    description: 'Euclidean distance tolerance'
    required: false
    default: "0.6"

outputs:
  message: 
    description: 'Output message'

runs:
  using: 'node20'
  main: 'dist/index.js'